### ISSUE TITLE
String schema format:date

### ISSUE THREAD

**Issue by danailch456** [krakenjs/hapi-openapi#188]
I have the following query parameter in the spec:
```
name: fromDate
in: query
description: A beginning date of the time range in yyyy-mm-dd format
required: false
schema:
  type: string
  format: date
````
When I setup the route with hapi-openapi and send a request with query `?fromDate=2014-10-14`, the validation passes successfully, but the route handler recieves `?fromDate=Tue+Oct+14+2014+03%3A00%3A00+GMT%2B0300+%28Eastern+European+Summer+Time%29`.
According to the openapi specification the ['date' format](https://swagger.io/docs/specification/data-models/data-types/#string)' should represent a date in yyyy-mm-dd.
Modifying the query params during validation seems odd and unnecessary. I hope this gets fixed soon.
