### ISSUE TITLE
does not validate a query parameter when a single item is sent

### ISSUE THREAD

**Issue by dcharbonnier** [krakenjs/hapi-openapi#199]
When you define an endpoint with:
```
parameters:
      - name: role
        schema:
          type: array
          items: 
            type: string
        required: false
        in: query
```

sending `?role=xxx` return a 400, `?role=xxx&role=yyy` works
