### ISSUE TITLE
header parameters should not be case sensitives

### ISSUE THREAD

**Issue by dcharbonnier** [krakenjs/hapi-openapi#200]
Fail :
```
- name: X-MyCustom-Header
  schema:
    type: string
  required: true
  in: header
```

Works :
```
- name: x-mycustom-header
  schema:
    type: string
  required: true
  in: header
```
