### ISSUE TITLE
serialization support

### ISSUE THREAD

**Issue by dcharbonnier** [krakenjs/hapi-openapi#208]
https://swagger.io/docs/specification/serialization/#query

Especially the deepObject is not supported.  
Example :
```
- in: query
  name: filter
  required: false
  schema:
    type: object
    properties:
      website:
        type: array
        items:
          type: string
      country:
        type: array
        items:
          type: string
  style: deepObject
```
the query `/1/stats/?filter%5Bwebsite%5D=a&filter%5Bwebsite%5D=b` is rejected with a 400
